name: Data Update

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Download data from Google sheets
        run: |
          mkdir -p data/
          curl -L -o data/sites.csv https://docs.google.com/spreadsheets/d/e/2PACX-1vQskn1VYGP0QpwFMSsLzQyvezxgvSZyO_WPCFQACXwwqTIsAuORA4apx-EPKtCHVqSWWkYfTU49C6qp/pub\?gid\=1772463569\&single\=true\&output\=csv
      - name: Add & commit
        id: add_commit
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: Automated
          committer_email: actions@users.noreply.github.com
          message: "Latest data"
